stages:
  - Dependencies

cache:
  paths:
    - node_modules/
    - public/

Dependencies:
  image: node:10.16.0
  stage: Dependencies
  script:
    - rm -Rf node_modules/
    - rm -Rf public/
    - npm install
    - npm run lint
    - npm run build
