image: node:latest
stages:
  - Build

Dependencies:
  image: ruby:latest
  stage: Build
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - npm install
    - npm run build
    - cd public
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
